export default {
  name: "backtester",
  __init__: "__init__",
  send: "send",
  set_error: "set_error",
  disconnect: "disconnect",
  changeStrategy: "changeStrategy",
  changeExchanges: "changeExchanges",
  changeSymbols: "changeSymbols",
  changePeriods: "changePeriods",
  updateRate:"updateRate",
  updateSlippage:"updateSlippage",
  updateSize:"updateSize",
  updatePricetick:"updatePricetick",
  updateCapital:"updateCapital",
};
