export default {
  name: "backtester",
  __init__: "__init__",
  send: "send",
  set_error: "set_error",
  disconnect: "disconnect",
  updateStrategy: "updateStrategy",
  changeExchanges: "changeExchanges",
  changeSymbols: "changeSymbols",
  changePeriods: "changePeriods",
  updateRate: "updateRate",
  updateSlippage: "updateSlippage",
  updateSize: "updateSize",
  updatePricetick: "updatePricetick",
  updateCapital: "updateCapital",
  update_start_datetime: "update_start_datetime",
  update_end_datetime: "update_end_datetime",
  update_inverse_mode_selected: "update_inverse_mode_selected",
  update_backtest_mode_selected: "update_backtest_mode_selected",
  update_dialog_strategy_setting:"update_dialog_strategy_setting"
};
